require("lspaccatrosi16.config.lualine")
require("lspaccatrosi16.config.generic")
require("lspaccatrosi16.config.lsp")
require("lspaccatrosi16.config.jdtls")
require("lspaccatrosi16.config.nightfox")
require("lspaccatrosi16.config.toggleterm")
require("lspaccatrosi16.config.treesitter")
